<!-- Generated by figma2htmlv1.1.0 on 2026-05-05 07:07 -->
<script>
	import { onMount } from 'svelte';
	onMount(() => {
		((t) => {
			if (!('querySelector' in document)) return;
			const e = (t) => {
					const e = t.getAttribute('data-src');
					e && t.getAttribute('src') != e && t.setAttribute('src', e);
				},
				i = (t) => {
					t.reduce((t, e) => t || e.isIntersecting, !1) && ((c = !1), r());
				},
				s = (t, e) => (e ? Array.prototype.slice.call(e.querySelectorAll(t)) : []),
				r = () => {
					const t = s(`.${o}artboard:where([data-min-width],[data-max-width])`, a),
						n = Math.min(Math.round(a.offsetWidth), window.innerWidth);
					t.forEach(function (t) {
						const i = t.getAttribute('data-min-width'),
							r = t.getAttribute('data-max-width');
						+i <= n && (+r >= n || null === r)
							? (c || s(`.${o}f2h-img`, t).forEach(e), (t.style.display = 'block'))
							: (t.style.display = 'none');
					}),
						c &&
							!l &&
							(((t) => {
								const e = t.getBoundingClientRect();
								return e.top < window.innerHeight && e.bottom > 0;
							})(a)
								? ((c = !1), r())
								: ((l = new IntersectionObserver(i, { rootMargin: '400px 400px' })), l.observe(a)));
				},
				a = document.getElementById(t),
				n = ((t, e) => {
					let i = null,
						s = 0;
					const r = () => {
						(s = Date.now()), (i = null), t();
					};
					return function () {
						const t = e - (Date.now() - s);
						t <= 0 || t > e ? (clearTimeout(i), r()) : i || (i = setTimeout(r, t));
					};
				})(r, 200),
				o = '';
			let l,
				c = !!window.IntersectionObserver;
			r(), document.addEventListener('DOMContentLoaded', r), window.addEventListener('resize', n);
		})('sumatran-tree-loss-box', {
			namespace: '',
			setup: window.setupInteractive || window.getComponent
		});
		const apiLink = document.createElement('link');
		apiLink.rel = 'preconnect';
		apiLink.href = 'https://fonts.googleapis.com';

		const gstaticLink = document.createElement('link');
		gstaticLink.rel = 'preconnect';
		gstaticLink.href = 'https://fonts.gstatic.com';
		gstaticLink.crossorigin = true;

		// const fontLink = document.createElement('link');
		// fontLink.rel = 'stylesheet';
		// fontLink.href =
		// 	'https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400&family=Roboto+Mono:ital,wght@0,500&family=Inter+Semi:ital,wght@0,700&display=swap';

		document.head.appendChild(apiLink);
		document.head.appendChild(gstaticLink);
		document.head.appendChild(fontLink);
	});
</script>

<div id="sumatran-tree-loss-box" class="figma2html">
	<!-- Frame: 1080px -->
	<div
		id="f2h-frame-1080"
		class="f2h-frame frame artboard"
		data-aspect-ratio="1.61"
		data-min-width="0"
	>
		<div class="spacer" style="padding: 0 0 0 0; min-width: 1080px; max-width: none;"></div>

		<picture>
			<img
				id="img-f2h-frame-1080"
				class="f2h-img"
				alt="Primary forest loss in Aceh, North Sumatra, and West Sumatra between 2001 - 2024"
				data-src="/figma/cyclone-senyar/sumatran-tree-loss/1080px.png"
				src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw=="
				loading="lazy"
				draggable="false"
				decoding="async"
				width="1080.00"
				height="null"
			/>
		</picture>

		<!-- Unified SVG Text Overlay -->
		<svg
			width="100%"
			height="100%"
			style="position: absolute; top: 0; left: 0; pointer-events: none; overflow: visible;"
		>
			<!-- Legend & Titles (No Outline) -->
			<text x="91.98%" y="94.00%" class="chart-legend">50 km</text>
			<text x="72.22%" y="8.89%" class="chart-title">West Sumatra</text>
			<text x="5.49%" y="8.89%" class="chart-title">Aceh</text>
			<text x="44.15%" y="8.89%" class="chart-title">North Sumatra</text>

			<!-- Areas of Interest -->
			<text
				x="82.90%"
				y="61.01%"
				class="area-of-interest outline"
				text-anchor="end"
				dominant-baseline="middle">AGAM</text
			>
			<text
				x="25.87%"
				y="26.73%"
				class="area-of-interest outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="25.87%" dy="-0.6em">NORTH</tspan><tspan x="25.87%" dy="1.2em">ACEH</tspan>
			</text>
			<text
				x="39.73%"
				y="62.35%"
				class="area-of-interest outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="39.73%" dy="-0.6em">ACEH</tspan>
				<tspan x="39.73%" dy="1.2em">TAMIANG</tspan>
			</text>
			<text
				x="50.57%"
				y="43.31%"
				class="area-of-interest outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="50.57%" dy="-0.6em">CENTRAL</tspan><tspan x="50.57%" dy="1.2em">TAPANULI</tspan>
			</text>
			<text
				x="66.45%"
				y="48.25%"
				class="area-of-interest outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="66.45%" dy="-0.6em">SOUTH</tspan>
				<tspan x="66.45%" dy="1.2em">TAPANULI</tspan>
			</text>

			<!-- Admin Labels -->
			<text
				x="94.22%"
				y="58.45%"
				class="admin-label outline"
				text-anchor="middle"
				dominant-baseline="middle">Bukittinggi</text
			>
			<text
				x="89.65%"
				y="24.51%"
				class="admin-label outline"
				text-anchor="middle"
				dominant-baseline="middle">Pasaman</text
			>

			<!-- Multiline Admin Labels -->
			<text
				x="88.31%"
				y="72.66%"
				class="admin-label outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="88.31%" dy="-0.6em">Padang</tspan>
				<tspan x="88.31%" dy="1.2em">Pariaman</tspan>
			</text>
			<text
				x="78.84%"
				y="35.86%"
				class="admin-label outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="78.84%" dy="-0.6em">Pasaman</tspan>
				<tspan x="78.84%" dy="1.2em">Barat</tspan>
			</text>
			<text
				x="63.37%"
				y="42.87%"
				class="admin-label outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="63.37%" dy="-0.6em">Padang</tspan>
				<tspan x="63.37%" dy="1.2em">Sidempuan</tspan>
			</text>
			<text
				x="57.86%"
				y="21.67%"
				class="admin-label outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="57.86%" dy="-0.6em">North</tspan>
				<tspan x="57.86%" dy="1.2em">Tapanuli</tspan>
			</text>
			<text
				x="64.41%"
				y="63.21%"
				class="admin-label outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="64.41%" dy="-0.6em">Mandailing</tspan>
				<tspan x="64.41%" dy="1.2em">Natal</tspan>
			</text>

			<!-- Eco Loss -->
			<text
				x="84.90%"
				y="70.87%"
				class="eco-loss outline"
				text-anchor="end"
				dominant-baseline="middle"
			>
				<tspan x="84.90%" dy="-0.6em">MANINJAU</tspan><tspan x="84.90%" dy="1.2em">CRATER</tspan>
			</text>
			<text
				x="74.49%"
				y="20.94%"
				class="eco-loss outline"
				text-anchor="start"
				dominant-baseline="middle"
			>
				<tspan x="74.49%" dy="-0.6em">AIR BANGIS</tspan>
				<tspan x="74.49%" dy="1.2em">FOREST COMPLEX</tspan>
			</text>
			<text
				x="20.05%"
				y="21.81%"
				class="eco-loss outline"
				text-anchor="end"
				dominant-baseline="middle"
			>
				<tspan x="20.05%" dy="-0.6em">SAMARKILANG</tspan>
				<tspan x="20.05%" dy="1.2em">FOREST COMPLEX</tspan>
			</text>
			<text
				x="38.39%"
				y="46.32%"
				class="eco-loss outline"
				text-anchor="start"
				dominant-baseline="middle"
			>
				<tspan x="38.39%" dy="-0.6em">TENGGULUN</tspan>
				<tspan x="38.39%" dy="1.2em">FOREST CORRIDOR</tspan>
			</text>
			<text
				x="35.80%"
				y="40.18%"
				class="eco-loss outline"
				text-anchor="start"
				dominant-baseline="middle"
			>
				<tspan x="35.80%" dy="-0.6em">LOKOP FOREST</tspan>
				<tspan x="35.80%" dy="1.2em">BLOCK</tspan>
			</text>
			<text
				x="48.33%"
				y="31.39%"
				class="eco-loss outline"
				text-anchor="end"
				dominant-baseline="middle"
			>
				<tspan x="48.33%" dy="-0.6em">BATANG TORU</tspan><tspan x="48.33%" dy="1.2em">FOREST COMPLEX</tspan>
			</text>

			<!-- 3-Line Eco Loss Labels -->
			<text
				x="80.30%"
				y="51.47%"
				class="eco-loss outline"
				text-anchor="end"
				dominant-baseline="middle"
			>
				<tspan x="80.30%" dy="-1.2em">MOUNT TALAKMAU</tspan><tspan x="80.30%" dy="1.2em">&amp; PASAMAN</tspan><tspan x="80.30%" dy="1.2em">COMPLEX</tspan>
			</text>
			<text
				x="51.94%"
				y="52.59%"
				class="eco-loss outline"
				text-anchor="end"
				dominant-baseline="middle"
			>
				<tspan x="51.94%" dy="-1.2em">MUARA BATANG</tspan><tspan x="51.94%" dy="1.2em">TORU PEAT</tspan><tspan x="51.94%" dy="1.2em">SWAMP FOREST</tspan>
			</text>
			<text x="53.26%" y="62.69%" class="eco-loss outline" text-anchor="end" dominant-baseline="middle">
				<tspan x="53.26%" dy="-1.2em">MUARA BATANG</tspan><tspan x="53.26%" dy="1.2em">GADIS PEAT</tspan><tspan x="53.26%" dy="1.2em">SWAMP FOREST</tspan>
			</text>

			<!-- Extra Labels -->
			<text
				x="27.94%"
				y="56.44%"
				class="eco-label outline"
				text-anchor="middle"
				dominant-baseline="middle"
			>
				<tspan x="27.94%" dy="-0.6em">Leuser</tspan>
				<tspan x="27.94%" dy="1.2em">Ecosystem</tspan>
			</text>
		</svg>
	</div>
</div>

<!-- End figma2htmlv1.1.0 generated content - 2026-05-05 07:07 -->

<style>
	#sumatran-tree-loss-box {
		max-width: none;
		margin: 0 auto;
	}

	#sumatran-tree-loss-box .f2h-frame {
		margin: 0 auto;
	}
	#sumatran-tree-loss-box text {
    	pointer-events: auto;
	}
	#sumatran-tree-loss-box p,
	#sumatran-tree-loss-box .f2h-img {
		width: 100% !important;
		top: 0;
	}

	#sumatran-tree-loss-box :where(.frame, .f2h-text) {
		position: absolute;
	}

	#sumatran-tree-loss-box :where(.f2h-img) {
		display: block;
	}

	#f2h-frame-1080 {
		position: relative;
		overflow: hidden;
		display: none;
	}

	#f2h-frame-1080 .chart-legend {
		font-family: 'Inter', sans-serif;
		font-weight: 400;
		font-size: 0.86rem;
		fill: rgba(102, 102, 102, 1);
	}

	#f2h-frame-1080 .area-of-interest {
		font-family: 'DM Mono', monospace;
		font-weight: 500;
		font-size: 0.72rem;
		letter-spacing: 0.2px;
		fill: rgba(215, 86, 56, 1);
	}

	#f2h-frame-1080 .chart-title {
		font-family: 'Inter', sans-serif;
		font-weight: 600;
		font-size: 0.86rem;
		fill: rgba(0, 0, 0, 1);
	}

	#f2h-frame-1080 .admin-label {
		font-family: 'DM Mono', monospace;
		font-weight: 400;
		font-size: 0.72rem;
		fill: rgba(102, 102, 102, 1);
	}

	#f2h-frame-1080 .eco-loss {
		font-family: 'DM Mono', monospace;
		font-weight: 400;
		font-size: 0.64rem;
		text-transform: uppercase;
		fill: #202020;
	}

	#f2h-frame-1080 .eco-label {
		font-family: 'DM Mono', monospace;
		font-weight: 400;
		font-size: 0.72rem;
		fill: rgba(102, 102, 102, 1);
	}

	#f2h-frame-1080 .outline {
		stroke: #ffffff;
		stroke-width: 3px;
		stroke-linejoin: round;
		paint-order: stroke fill;
	}
</style>
