<!-- Generated by figma2htmlv1.1.0 on 2026-03-31 14:59 -->
<script>
	import { onMount, tick } from 'svelte';

	onMount(async () => {
		await tick();

		((t) => {
			if (!('querySelector' in document)) return;
			const e = (t) => {
					const e = t.getAttribute('data-src');
					e && t.getAttribute('src') != e && t.setAttribute('src', e);
				},
				i = (t) => {
					t.reduce((t, e) => t || e.isIntersecting, !1) && ((c = !1), r());
				},
				s = (t, e) => (e ? Array.prototype.slice.call(e.querySelectorAll(t)) : []),
				r = () => {
					const t = s(`.${o}artboard:where([data-min-width],[data-max-width])`, a),
						n = Math.min(Math.round(a.offsetWidth), window.innerWidth);
					t.forEach(function (t) {
						const i = t.getAttribute('data-min-width'),
							r = t.getAttribute('data-max-width');
						+i <= n && (+r >= n || null === r)
							? (c || s(`.${o}f2h-img`, t).forEach(e), (t.style.display = 'block'))
							: (t.style.display = 'none');
					}),
						c &&
							!l &&
							(((t) => {
								const e = t.getBoundingClientRect();
								return e.top < window.innerHeight && e.bottom > 0;
							})(a)
								? ((c = !1), r())
								: ((l = new IntersectionObserver(i, { rootMargin: '400px 400px' })), l.observe(a)));
				},
				a = document.getElementById(t),
				n = ((t, e) => {
					let i = null,
						s = 0;
					const r = () => {
						(s = Date.now()), (i = null), t();
					};
					return function () {
						const t = e - (Date.now() - s);
						t <= 0 || t > e ? (clearTimeout(i), r()) : i || (i = setTimeout(r, t));
					};
				})(r, 200),
				o = '';
			let l,
				c = !!window.IntersectionObserver;
			r(), document.addEventListener('DOMContentLoaded', r), window.addEventListener('resize', n);
		})('sumatran-flood-2025-box', {
			namespace: '',
			setup: window.setupInteractive || window.getComponent
		});

		const apiLink = document.createElement('link');
		apiLink.rel = 'preconnect';
		apiLink.href = 'https://fonts.googleapis.com';

		const gstaticLink = document.createElement('link');
		gstaticLink.rel = 'preconnect';
		gstaticLink.href = 'https://fonts.gstatic.com';
		gstaticLink.crossorigin = true;

		const fontLink = document.createElement('link');
		fontLink.rel = 'stylesheet';
		fontLink.href =
			'https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400&family=Inter+Semi:ital,wght@0,700&display=swap';

		document.head.appendChild(apiLink);
		document.head.appendChild(gstaticLink);
		document.head.appendChild(fontLink);

		setTimeout(() => {
			window.dispatchEvent(new Event('resize'));
		}, 50);
	});
</script>

<div id="sumatran-flood-2025-box" class="figma2html">
	<!-- Frame: 1080px -->
	<div
		id="f2h-frame-1080"
		class="f2h-frame frame artboard"
		data-aspect-ratio="0.785"
		data-min-width="0"
	>
		<div class="spacer" style="padding: 0 0 0 0; min-width: 1080px; max-width: none;"></div>
		<picture>
			<img
				id="img-f2h-frame-1080"
				class="f2h-img"
				alt="Sumatran flood map 2025 cyclone senyar"
				data-src="/figma/cyclone-senyar/sumatran-flood-2025/1080px.png"
				src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw=="
				loading="lazy"
				draggable="false"
				decoding="async"
				width="1080.00"
				height="null"
			/>
		</picture>
		<div
			class="f2h-text undefined"
			style="top: 13.85%; left: 21.87%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Lhokseumawe</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 18.24%; left: 32.82%; opacity: 1; width: 46.69px; transform: translate(-50%, -50%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Aceh Timur</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 21.20%; left: 26.43%; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-province">ACEH</p>
		</div>
		<!-- <div
			class="f2h-text undefined"
			style="top: 18.40%; left: 53.89%; opacity: 1; width: 138.57px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-mapcomp">MALACCA STRAIT</p>
		</div> -->
		<div
			class="f2h-text undefined"
			style="top: 6.12%; left: 42.78%; opacity: 1; width: 25.70px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;"
		>
			<p class="f2h-legend-label">0</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 7.55%; left: 42.78%; opacity: 1; width: 275.72px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;"
		>
			<p class="f2h-legend-label">people per 100 squared meters</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 3.75%; left: 42.78%; opacity: 1; width: 275.72px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;"
		>
			<p class="f2h-legend-title"><span style="font-weight: 600">Population Density</span></p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 3.75%; left: 62.83%; opacity: 1; width: 209.43px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;"
		>
			<p class="f2h-legend-title"><span style="font-weight: 600">Flood Extent</span></p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 6.12%; left: 46.68%; opacity: 1; width: 25.70px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;"
		>
			<p class="f2h-legend-label">5</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 6.12%; left: 50.58%; opacity: 1; width: 25.70px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;"
		>
			<p class="f2h-legend-label">10</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 6.12%; left: 54.47%; opacity: 1; width: 25.70px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;"
		>
			<p class="f2h-legend-label">15+</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 35.75%; left: 46.44%; opacity: 1; width: 100.68px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-province">SUMATERA UTARA</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 54.21%; left: 59.56%; opacity: 1; width: 100.68px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-province">SUMATERA BARAT</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 50.24%; left: 72.41%; opacity: 1; width: 100.68px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-province">RIAU</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 66.43%; left: 79.50%; opacity: 1; width: 100.68px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-province">JAMBI</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 78.81%; left: 74.28%; opacity: 1; width: 100.68px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-province">BENGKULU</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 19.31%; left: 37.54%; opacity: 1; width: 50.05px; transform: translate(-50%, -50%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Langsa</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 22.88%; left: 33.17%; opacity: 1; width: 50.05px; transform: translate(-50%, -50%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Aceh Tamiang</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 27.34%; left: 40.47%; opacity: 1; width: 50.05px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Medan</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 23.31%; left: 41.81%; opacity: 1; width: 50.05px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Langkat</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 26.08%; left: 49.23%; opacity: 1; width: 50.05px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Serdang Bedagai</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 29.59%; left: 54.19%; opacity: 1; width: 50.05px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Batubara</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 43.65%; left: 41.84%; opacity: 1; width: 66.11px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Tapanuli Selatan</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 48.01%; left: 43.73%; opacity: 1; width: 66.11px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Mandailing Natal</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 50.58%; left: 51.86%; opacity: 1; width: 66.11px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Pasaman Barat</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 55.45%; left: 51.13%; opacity: 1; width: 71.89px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Pariaman</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 58.42%; left: 58.25%; opacity: 1; width: 71.89px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Padang</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 63.80%; left: 63.57%; opacity: 1; width: 71.89px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Pesisir Selatan</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 15.89%; left: 16.08%; opacity: 1; width: 44.49px; transform: translate(-50%, -50%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Sigli</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 22.4%; left: 17.84%; opacity: 1; width: 49.47px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Aceh Barat</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 36.27%; left: 32.58%; opacity: 1; width: 49.47px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Aceh Singkil</p>
		</div>
		<div
			class="f2h-text undefined"
			style="top: 11.24%; left: 10.22%; opacity: 1; width: 50.05px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: center;"
		>
			<p class="f2h-poi">Banda Aceh</p>
		</div>
	</div>
</div>

<!-- End figma2htmlv1.1.0 generated content - 2026-03-31 14:59 -->

<style>
	#sumatran-flood-2025-box {
		max-width: 1160px;
		margin: 0 auto;
	}

	#sumatran-flood-2025-box .f2h-frame {
		margin: 0 auto;
	}

	#sumatran-flood-2025-box p,
	#sumatran-flood-2025-box .body {
		margin: 0;
	}

	#sumatran-flood-2025-box .f2h-img {
		width: 100% !important;
		top: 0;
	}

	#sumatran-flood-2025-box .f2h-symbol {
		box-sizing: border-box;
	}

	#sumatran-flood-2025-box :where(.frame, .f2h-text, .f2h-symbol) {
		position: absolute;
	}

	#sumatran-flood-2025-box :where(.f2h-link, .f2h-img) {
		display: block;
	}

	#f2h-frame-1080 {
		position: relative;
		overflow: hidden;
		display: none;
	}

	#f2h-frame-1080 .f2h-poi {
		font-family: Inter;
		font-style: normal;
		font-weight: 400;
		font-size: 0.72rem;
		text-decoration: none;
		text-transform: none;
		line-height: normal;
		letter-spacing: 0px;
		color: rgba(52, 52, 52, 1);
		mix-blend-mode: normal;
	}
	#f2h-frame-1080 .f2h-mapcomp {
		font-family: Inter;
		font-style: normal;
		font-weight: 400;
		font-size: 0.86rem;
		text-decoration: none;
		text-transform: none;
		line-height: normal;
		letter-spacing: 0.24rem;
		color: rgba(52, 52, 52, 0.6);
		mix-blend-mode: normal;
	}
	#f2h-frame-1080 .f2h-legend-label {
		font-family: Inter;
		font-style: normal;
		font-weight: 400;
		font-size: 0.72rem;
		text-decoration: none;
		text-transform: none;
		line-height: normal;
		letter-spacing: 0px;
		color: rgba(52, 52, 52, 1);
		mix-blend-mode: normal;
	}
	#f2h-frame-1080 .f2h-legend-title {
		font-family: Inter;
		font-style: normal;
		font-weight: 600;
		font-size: 0.86rem;
		text-decoration: none;
		text-transform: none;
		line-height: normal;
		letter-spacing: 0px;
		color: rgba(102, 102, 102, 1);
		mix-blend-mode: normal;
	}

	#f2h-frame-1080 .f2h-province {
		font-family: Inter;
		font-style: normal;
		font-weight: 300;
		font-size: 0.86rem;
		text-decoration: none;
		text-transform: none;
		line-height: normal;
		letter-spacing: 0.24rem;
		color: rgba(52, 52, 52, 0.6);
		mix-blend-mode: normal;
	}
	#sumatran-flood-2025-box p:not(
    .f2h-legend-title,
    .f2h-legend-label
) {
		text-shadow:
			-2px -2px 0 #ffffff,
			0px -2px 0 #ffffff,
			2px -2px 0 #ffffff,
			2px 0px 0 #ffffff,
			2px 2px 0 #ffffff,
			0px 2px 0 #ffffff,
			-2px 2px 0 #ffffff,
			-2px 0px 0 #ffffff;
	}
</style>
