<!-- Generated by figma2htmlv1.1.0 on 2025-09-27 23:56 -->
<script>import { onMount } from "svelte";onMount(() => {(t=>{if(!("querySelector"in document))return;const e=t=>{const e=t.getAttribute("data-src");e&&t.getAttribute("src")!=e&&t.setAttribute("src",e)},i=t=>{t.reduce(((t,e)=>t||e.isIntersecting),!1)&&(c=!1,r())},s=(t,e)=>e?Array.prototype.slice.call(e.querySelectorAll(t)):[],r=()=>{const t=s(`.${o}artboard:where([data-min-width],[data-max-width])`,a),n=Math.min(Math.round(a.offsetWidth),window.innerWidth);t.forEach((function(t){const i=t.getAttribute("data-min-width"),r=t.getAttribute("data-max-width");+i<=n&&(+r>=n||null===r)?(c||s(`.${o}f2h-img`,t).forEach(e),t.style.display="block"):t.style.display="none"})),c&&!l&&((t=>{const e=t.getBoundingClientRect();return e.top<window.innerHeight&&e.bottom>0})(a)?(c=!1,r()):(l=new IntersectionObserver(i,{rootMargin:"400px 400px"}),l.observe(a)))},a=document.getElementById(t),n=((t,e)=>{let i=null,s=0;const r=()=>{s=Date.now(),i=null,t()};return function(){const t=e-(Date.now()-s);t<=0||t>e?(clearTimeout(i),r()):i||(i=setTimeout(r,t))}})(r,200),o="";let l,c=!!window.IntersectionObserver;r(),document.addEventListener("DOMContentLoaded",r),window.addEventListener("resize",n)})("asset-web-box", {namespace: "", setup: window.setupInteractive || window.getComponent});
  const apiLink = document.createElement('link');
  apiLink.rel = 'preconnect';
  apiLink.href = 'https://fonts.googleapis.com';

  const gstaticLink = document.createElement('link');
  gstaticLink.rel = 'preconnect';
  gstaticLink.href = 'https://fonts.gstatic.com';
  gstaticLink.crossorigin = true

  const fontLink = document.createElement('link');
  fontLink.rel = 'stylesheet';
  fontLink.href = 'https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,300;0,400&family=Inter+Semi:ital,wght@0,700&display=swap';

  document.head.appendChild(apiLink);
  document.head.appendChild(gstaticLink);
  document.head.appendChild(fontLink);
})</script><div id="asset-web-box" class="figma2html">


<!-- Frame: 1080px -->
<div id="f2h-frame-1080" class="f2h-frame frame artboard" data-aspect-ratio="1.508" data-min-width="1080" style="width: 1080px;">
  <div class="spacer" style="padding: 0 0 0 0; min-width: 1080px; max-width: none;"></div>
  <picture>
    <img id="img-f2h-frame-1080" class="f2h-img" alt="Local adoption of climate change action" data-src="/figma/pacific-dataviz-2025/drr-adoption/1080px.png" src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw==" loading="lazy" draggable="false" decoding="async" width="1080.00" height="716.00"/>
  </picture>
<div class="f2h-text undefined" style="top: 32.96%; left: 68.43%; opacity: 1; width: 62.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-0">Kiribati</p>
  </div>
<div class="f2h-text undefined" style="top: 18.58%; left: 65.46%; opacity: 1; width: 62.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-1">Marshall Island</p>
  </div>
<div class="f2h-text undefined" style="top: 41.20%; left: 13.52%; opacity: 1; width: 83.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-2">Papua New Guinea</p>
  </div>
<div class="f2h-text undefined" style="top: 40.92%; left: 44.54%; opacity: 1; width: 72.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-3">Solomon Islands</p>
  </div>
<div class="f2h-text undefined" style="top: 69.13%; left: 65.00%; opacity: 1; width: 62.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-4">Fiji</p>
  </div>
<div class="f2h-text undefined" style="top: 16.34%; left: 13.52%; opacity: 1; width: 62.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-5">Palau</p>
  </div>
<div class="f2h-text undefined" style="top: 23.18%; left: 13.52%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-6"><span style="font-weight: 600">16</span> <span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;">of 16</span></p>
  </div>
<div class="f2h-text undefined" style="top: 20.95%; left: 13.52%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-7"><span style="font-weight: 600">100%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 48.74%; left: 13.52%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-8"><span style="font-weight: 600">0</span> of 22</p>
  </div>
<div class="f2h-text undefined" style="top: 46.51%; left: 13.52%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-9"><span style="font-weight: 600">0%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 46.79%; left: 44.54%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-10"><span style="font-weight: 600">0</span> of 10</p>
  </div>
<div class="f2h-text undefined" style="top: 44.55%; left: 44.54%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-11"><span style="font-weight: 600">0%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 36.73%; left: 56.76%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-12"><span style="font-weight: 600">0</span> of 14</p>
  </div>
<div class="f2h-text undefined" style="top: 34.50%; left: 56.76%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-13"><span style="font-weight: 600">0%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 26.12%; left: 65.46%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-14"><span style="font-weight: 600">18</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 24</span></p>
  </div>
<div class="f2h-text undefined" style="top: 23.88%; left: 65.46%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-15"><span style="font-weight: 600">75.0%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 40.50%; left: 68.43%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-16"><span style="font-weight: 600">6</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 23</span></p>
  </div>
<div class="f2h-text undefined" style="top: 38.27%; left: 68.43%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-17"><span style="font-weight: 600">26.1%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 55.45%; left: 67.22%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-18"><span style="font-weight: 600">8</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 8</span></p>
  </div>
<div class="f2h-text undefined" style="top: 53.21%; left: 67.22%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-19"><span style="font-weight: 600">100%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 72.77%; left: 50.37%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-20"><span style="font-weight: 600">6</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 6</span></p>
  </div>
<div class="f2h-text undefined" style="top: 70.53%; left: 50.37%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-21"><span style="font-weight: 600">100%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 75.56%; left: 65.00%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-22"><span style="font-weight: 600">0</span> of 14</p>
  </div>
<div class="f2h-text undefined" style="top: 73.32%; left: 65.00%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-23"><span style="font-weight: 600">0%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 63.55%; left: 81.48%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-24"><span style="font-weight: 600">12</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 362</span></p>
  </div>
<div class="f2h-text undefined" style="top: 61.31%; left: 81.48%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-25"><span style="font-weight: 600">3.3%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 89.94%; left: 79.81%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-26"><span style="font-weight: 600">54</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 161</span></p>
  </div>
<div class="f2h-text undefined" style="top: 87.71%; left: 79.81%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-27"><span style="font-weight: 600">33.5%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 30.03%; left: 36.57%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-28"><span style="font-weight: 600">7</span> <span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;">of 60</span></p>
  </div>
<div class="f2h-text undefined" style="top: 27.79%; left: 36.57%; opacity: 1; width: 63.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-29"><span style="font-weight: 600">11.7%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 66.70%; left: 50.37%; opacity: 1; width: 71.79px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-30">Vanuatu</p>
  </div>
<div class="f2h-text undefined" style="top: 49.58%; left: 67.22%; opacity: 1; width: 50.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-31">Tuvalu</p>
  </div>
<div class="f2h-text undefined" style="top: 30.03%; left: 56.76%; opacity: 1; width: 62.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-32">Nauru</p>
  </div>
<div class="f2h-text undefined" style="top: 70.53%; left: 79.81%; opacity: 1; width: 62.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-33">Tonga</p>
  </div>
<div class="f2h-text undefined" style="top: 26.54%; left: 81.48%; opacity: 1; width: 62.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-34">Samoa</p>
  </div>
<div class="f2h-text undefined" style="top: 20.11%; left: 36.57%; opacity: 1; width: 101.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-35">Federated States of Micronesia</p>
  </div>
<div class="f2h-text undefined" style="top: 9.22%; left: 46.20%; opacity: 1; width: 152.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-36"><span style="font-weight: 300">Each square represents one local government.</span></p>
  </div>
<div class="f2h-text undefined" style="top: 9.08%; left: 22.96%; opacity: 1; width: 114.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-37"><span style="font-weight: 600">Blue</span><span style="font-family: Inter; font-style: normal; font-weight: 300; font-size: 12px; text-decoration: none; text-transform: none; line-height: 18px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal;">: disaster risk reduction strategy adopted</span></p>
  </div>
<div class="f2h-text undefined" style="top: 14.66%; left: 77.31%; opacity: 1; width: 114.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-38"><span style="font-weight: 600">Grey</span><span style="font-family: Inter; font-style: normal; font-weight: 300; font-size: 12px; text-decoration: none; text-transform: none; line-height: 18px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal;">: not adopted</span></p>
  </div>
</div>



<!-- Frame: 393px -->
<div id="f2h-frame-393" class="f2h-frame frame artboard" data-aspect-ratio="0.355" data-max-width="1079" style="width: 393px;">
  <div class="spacer" style="padding: 0 0 0 0; min-width: 393px; max-width: 1079px;"></div>
  <picture>
    <img id="img-f2h-frame-393" class="f2h-img" alt="Local adoption of climate change action" data-src="/figma/pacific-dataviz-2025/drr-adoption/393px.png" src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw==" loading="lazy" draggable="false" decoding="async" width="393.00" height="1106.00"/>
  </picture>
<div class="f2h-text undefined" style="top: 17.54%; left: 50.00%; opacity: 1; width: 352.73px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;">
    <p class="f2h-text-0"><span style="font-weight: 600">Micronesia</span></p>
  </div>
<div class="f2h-text undefined" style="top: 23.39%; left: 83.15%; opacity: 1; width: 48.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-1">Marshall Island</p>
  </div>
<div class="f2h-text undefined" style="top: 26.50%; left: 83.15%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-2"><span style="font-weight: 600">75.0%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 27.68%; left: 83.15%; opacity: 1; width: 42.92px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-3"><span style="font-weight: 600">18</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 24</span></p>
  </div>
<div class="f2h-text undefined" style="top: 30.35%; left: 86.33%; opacity: 1; width: 48.05px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-4">Kiribati</p>
  </div>
<div class="f2h-text undefined" style="top: 34.66%; left: 86.33%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-5"><span style="font-weight: 600">6</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 23</span></p>
  </div>
<div class="f2h-text undefined" style="top: 33.46%; left: 86.33%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-6"><span style="font-weight: 600">26.1%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 22.32%; left: 4.64%; opacity: 1; width: 48.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-7">Palau</p>
  </div>
<div class="f2h-text undefined" style="top: 26.19%; left: 4.64%; opacity: 1; width: 48.00px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-8"><span style="font-weight: 600">16</span> <span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;">of 16</span></p>
  </div>
<div class="f2h-text undefined" style="top: 24.99%; left: 4.64%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-9"><span style="font-weight: 600">100%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 27.45%; left: 65.59%; opacity: 1; width: 48.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-10">Nauru</p>
  </div>
<div class="f2h-text undefined" style="top: 31.28%; left: 65.59%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-11"><span style="font-weight: 600">0</span> of 14</p>
  </div>
<div class="f2h-text undefined" style="top: 30.13%; left: 65.59%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-12"><span style="font-weight: 600">0%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 23.76%; left: 35.76%; opacity: 1; width: 88.21px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-13">Federated States of Micronesia</p>
  </div>
<div class="f2h-text undefined" style="top: 29.39%; left: 35.76%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-14"><span style="font-weight: 600">7</span> <span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;">of 60</span></p>
  </div>
<div class="f2h-text undefined" style="top: 28.17%; left: 35.76%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-15"><span style="font-weight: 600">11.7%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 71.86%; left: 50.00%; opacity: 1; width: 192.45px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;">
    <p class="f2h-text-16"><span style="font-weight: 600">Polynesia</span></p>
  </div>
<div class="f2h-text undefined" style="top: 85.65%; left: 34.27%; opacity: 1; width: 46.55px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-17">Tonga</p>
  </div>
<div class="f2h-text undefined" style="top: 94.84%; left: 34.27%; opacity: 1; width: 46.35px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-18"><span style="font-weight: 600">33.5%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 96.01%; left: 34.27%; opacity: 1; width: 46.35px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-19"><span style="font-weight: 600">54</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 161</span></p>
  </div>
<div class="f2h-text undefined" style="top: 79.57%; left: 19.08%; opacity: 1; width: 36.52px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-20">Tuvalu</p>
  </div>
<div class="f2h-text undefined" style="top: 81.81%; left: 19.08%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-21"><span style="font-weight: 600">100%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 82.99%; left: 19.08%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-22"><span style="font-weight: 600">8</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 8</span></p>
  </div>
<div class="f2h-text undefined" style="top: 76.17%; left: 64.14%; opacity: 1; width: 44.76px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-23">Samoa</p>
  </div>
<div class="f2h-text undefined" style="top: 94.04%; left: 64.14%; opacity: 1; width: 44.76px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-24"><span style="font-weight: 600">3.3%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 95.22%; left: 64.14%; opacity: 1; width: 50.14px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-25"><span style="font-weight: 600">12</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 362</span></p>
  </div>
<div class="f2h-text undefined" style="top: 3.07%; left: 19.53%; opacity: 1; width: 108.64px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-26"><span style="font-weight: 300">Disaster risk reduction strategy adopted</span></p>
  </div>
<div class="f2h-text undefined" style="top: 3.07%; left: 64.67%; opacity: 1; width: 108.60px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-27"><span style="font-weight: 300">Disaster risk reduction strategy not adopted</span></p>
  </div>
<div class="f2h-text undefined" style="top: 11.21%; left: 19.53%; opacity: 1; width: 279.18px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-28"><span style="font-weight: 300">Each square represents one local government.</span></p>
  </div>
<div class="f2h-text undefined" style="top: 41.56%; left: 50.00%; opacity: 1; width: 325.73px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center;">
    <p class="f2h-text-29"><span style="font-weight: 600">Melanesia</span></p>
  </div>
<div class="f2h-text undefined" style="top: 58.56%; left: 83.70%; opacity: 1; width: 48.22px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-30">Fiji</p>
  </div>
<div class="f2h-text undefined" style="top: 62.39%; left: 83.70%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-31"><span style="font-weight: 600">0</span> of 14</p>
  </div>
<div class="f2h-text undefined" style="top: 61.24%; left: 83.70%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-32"><span style="font-weight: 600">0%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 57.65%; left: 60.40%; opacity: 1; width: 48.00px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-33">Vanuatu</p>
  </div>
<div class="f2h-text undefined" style="top: 61.05%; left: 60.40%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-34"><span style="font-weight: 600">6</span><span style="font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal;"> of 6</span></p>
  </div>
<div class="f2h-text undefined" style="top: 59.89%; left: 60.40%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-35"><span style="font-weight: 600">100%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 47.41%; left: 1.70%; opacity: 1; width: 65.64px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-36">Papua New Guinea</p>
  </div>
<div class="f2h-text undefined" style="top: 51.70%; left: 1.70%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-37"><span style="font-weight: 600">0</span> of 22</p>
  </div>
<div class="f2h-text undefined" style="top: 50.52%; left: 1.70%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-38"><span style="font-weight: 600">0%</span></p>
  </div>
<div class="f2h-text undefined" style="top: 47.95%; left: 51.11%; opacity: 1; width: 56.48px; transform: translate(0%, -100%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-39">Solomon Islands</p>
  </div>
<div class="f2h-text undefined" style="top: 51.37%; left: 51.11%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-40"><span style="font-weight: 600">0</span> of 10</p>
  </div>
<div class="f2h-text undefined" style="top: 50.19%; left: 51.11%; opacity: 1; width: 36.52px; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
    <p class="f2h-text-41"><span style="font-weight: 600">0%</span></p>
  </div>
</div>
</div><style>	#asset-web-box { 
  max-width: none;
  margin: 0 auto;
}

#asset-web-box .f2h-frame {
  margin: 0 auto !important;
  
  width: 100% !important;

  max-width: var(--f2h-frame-max-width, 100%);
}

#f2h-frame-1080 {
  --f2h-frame-max-width: 1080px;
}

#f2h-frame-393 {
  --f2h-frame-max-width: 393px;
}

#asset-web-box p, #asset-web-box .body { 
  margin: 0;
}

#asset-web-box .f2h-img { 
  width: 100% !important;
  top: 0;
}

#asset-web-box .f2h-symbol { 
  box-sizing: border-box;
}

#asset-web-box :where(.frame, .f2h-text, .f2h-symbol) { 
  position: absolute;
}

#asset-web-box :where(.f2h-link, .f2h-img) { 
  display: block;
}



#f2h-frame-1080 { position: relative; overflow: hidden; display: none; }

#f2h-frame-1080 .f2h-text-0 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-1 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-2 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-3 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-4 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-5 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-6 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-7 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-8 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-9 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-10 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-11 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-12 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-13 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-14 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-15 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-16 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-17 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-18 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-19 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-20 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-21 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-22 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-23 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-24 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-25 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-26 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-27 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-28 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-29 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-30 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-31 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-32 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-33 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-34 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-35 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-36 { font-family: Inter; font-style: normal; font-weight: 300; font-size: 12px; text-decoration: none; text-transform: none; line-height: 18px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-37 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 18px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-1080 .f2h-text-38 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 18px; letter-spacing: 0px; color: rgba(217, 217, 217, 1); mix-blend-mode: normal; }

#f2h-frame-393 { position: relative; overflow: hidden; display: none; }

#f2h-frame-393 .f2h-text-0 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-1 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-2 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-3 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-4 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-5 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-6 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-7 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-8 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-9 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-10 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-11 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-12 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-13 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-14 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-15 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-16 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-17 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 9px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-18 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-19 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-20 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-21 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-22 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-23 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-24 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-25 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-26 { font-family: Inter; font-style: normal; font-weight: 300; font-size: 12px; text-decoration: none; text-transform: none; line-height: 18px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-27 { font-family: Inter; font-style: normal; font-weight: 300; font-size: 12px; text-decoration: none; text-transform: none; line-height: 18px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-28 { font-family: Inter; font-style: normal; font-weight: 300; font-size: 12px; text-decoration: none; text-transform: none; line-height: 18px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-29 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 12px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-30 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-31 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-32 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-33 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-34 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-35 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(13, 150, 249, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-36 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-37 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-38 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-39 { font-family: Inter; font-style: normal; font-weight: 400; font-size: 10px; text-decoration: none; text-transform: none; line-height: normal; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-40 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }
#f2h-frame-393 .f2h-text-41 { font-family: Inter; font-style: normal; font-weight: 600; font-size: 10px; text-decoration: none; text-transform: none; line-height: 9.274335861206055px; letter-spacing: 0px; color: rgba(102, 102, 102, 1); mix-blend-mode: normal; }</style>
<!-- End figma2htmlv1.1.0 generated content - 2025-09-27 23:56 -->